name: build and integrade image to Dockerhub

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: build docker image
      run: |
        docker build -t emeraude202/my_python_web_app_web:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: emeraude202
        password: dckr_pat_N3xbwHad-SIZ0UoiUtnZMhxgOn8

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      run: |
        docker push emeraude202/my_python_web_app_web:latest
        

       